#!/usr/bin/env python3
"""Regenerate crates/ui-egui/src/icon_data.rs from the two icon sources.

    scripts/gen-icon-table.py

* `assets/ico/<group>/<name>.svg` — PhotoSuite's icon library, embedded as
  `<group>-<name>` (so `tools/brush.svg` is `tools-brush`). Mostly Tabler Icons (MIT, see
  `assets/ico/LICENSE`) plus traced glyphs.
* `assets/icons/<name>.svg` — the Lucide set that came with the engine, embedded under its
  own name.

Files are embedded exactly as their authors wrote them; `icons::whiten` recolours them at load.
Run this after adding or removing an icon: anything not in the table simply is not available,
and `icons.rs` falls back to a square.
"""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
rows, seen = [], {}

for svg in sorted((root / "assets/ico").glob("*/*.svg")):
    name = f"{svg.parent.name}-{svg.stem}"
    seen[name] = svg
    rows.append((name, f"../../../assets/ico/{svg.parent.name}/{svg.name}"))

for svg in sorted((root / "assets/icons").glob("*.svg")):
    if svg.stem in seen:
        raise SystemExit(f"name clash: {svg} and {seen[svg.stem]}")
    rows.append((svg.stem, f"../../../assets/icons/{svg.name}"))

body = "\n".join(f'    ("{n}", include_bytes!("{p}")),' for n, p in sorted(rows))
(root / "crates/ui-egui/src/icon_data.rs").write_text(
    "//! Embedded icons, recoloured and tinted at runtime by [`crate::icons`].\n//!\n"
    "//! Generated by `scripts/gen-icon-table.py`; do not edit by hand. `<group>-<name>` entries\n"
    "//! come from PhotoSuite's library in `assets/ico/` (Tabler Icons, MIT, plus traced\n"
    "//! glyphs — see `assets/ico/LICENSE` and THIRD-PARTY-NOTICES.md); the rest are Lucide (ISC).\n\n"
    f"pub static ICONS: &[(&str, &[u8])] = &[\n{body}\n];\n"
)
print(f"icon_data.rs: {len(rows)} icons ({len(seen)} from assets/ico)")
