//! Menu commands and tools hidden by default.
//!
//! The engine carries Photoshop's full menu tree; PhotoSuite shows a smaller set by default.
//! These are the items hidden out of the box, re-showable in Edit › Menus and Edit › Toolbar
//! ("Show All Menu Items" clears the lot).
//!
//! Bump [`DEFAULTS_VERSION`] when the lists change and record the new menu ids in
//! [`HIDDEN_MENU_ADDED`]: preferences saved by an older version take those once, on load.

/// Incremented whenever the lists below change.
pub const DEFAULTS_VERSION: u32 = 3;

pub const HIDDEN_MENU_ITEMS: &[&str] = &[
    "edit.checkSpelling",
    "edit.presets.migratePresets",
    "edit.presets.presetManager",
    "edit.purge.clipboard",
    "edit.purge.videoCache",
    "edit.toggleLastState",
    "edit.transform.skew",
    "file.automate.batch",
    "file.automate.contactSheetII",
    "file.automate.photomerge",
    "file.export.artboardsToPdf",
    "file.import.variableDataSets",
    "file.import.wiaSupport",
    "file.package",
    "file.placeLinked",
    "file.revert",
    "file.saveACopy",
    "file.scripts.browse",
    "file.scripts.statistics",
    "filter.adaptiveWideAngle",
    "filter.blurGallery.tiltShift",
    "filter.distort.zigZag",
    "filter.other.hsbHsl",
    "filter.pixelate.facet",
    "filter.render.flame",
    "filter.render.pictureFrame",
    "filter.render.tree",
    "filter.stylize.extrude",
    "filter.stylize.solarize",
    "filter.vanishingPoint",
    "filter.video.deInterlace",
    "image.adjustments.equalize",
    "image.adjustments.hdrToning",
    "image.calculations",
    "image.mode.duotone",
    "image.mode.multichannel",
    "image.rotation.arbitrary",
    "image.trap",
    "image.variables.dataSets",
    "layer.matting.defringe",
    "layer.new.artboard",
    "layer.new.artboardFromGroup",
    "layer.rasterize.video",
    "layer.smartObjects.convertToEmbedded",
    "layer.smartObjects.convertToLinked",
    "layer.smartObjects.revealInFinder",
    "layer.smartObjects.stackMode.entropy",
    "layer.smartObjects.stackMode.kurtosis",
    "layer.smartObjects.stackMode.mean",
    "layer.smartObjects.stackMode.skewness",
    "layer.smartObjects.stackMode.standardDeviation",
    "layer.smartObjects.stackMode.summation",
    "layer.smartObjects.stackMode.variance",
    "layer.videoLayers.insertBlankFrame",
    "layer.videoLayers.interpretFootage",
    "layer.videoLayers.reloadFrame",
    "layer.videoLayers.restoreAllFrames",
    "layer.videoLayers.restoreFrame",
    "select.focusArea",
    "select.grow",
    "select.reselect",
    "select.similar",
    "select.sky",
    "select.subject",
    "type.antiAlias.crisp",
    "type.antiAlias.sharp",
    "type.antiAlias.smooth",
    "type.antiAlias.strong",
    "type.antiAlias.windows",
    "type.antiAlias.windowsLcd",
    "type.convertToParagraphText",
    "type.convertToPointText",
    "type.convertToShape",
    "type.createWorkPath",
    "type.fontPreviewSize.extraLarge",
    "type.fontPreviewSize.huge",
    "type.fontPreviewSize.large",
    "type.fontPreviewSize.medium",
    "type.fontPreviewSize.small",
    "type.languageOptions.defaultFeatures",
    "type.languageOptions.eastAsianFeatures",
    "type.languageOptions.middleEasternAndSouthAsianComposer",
    "type.languageOptions.middleEasternFeatures",
    "type.loadDefaultTypeStyles",
    "type.openType.contextualAlternates",
    "type.openType.discretionaryLigatures",
    "type.openType.fractions",
    "type.openType.oldstyle",
    "type.openType.ordinals",
    "type.openType.ornaments",
    "type.openType.standardLigatures",
    "type.openType.stylisticAlternates",
    "type.openType.swash",
    "type.openType.titlingAlternates",
    "type.orientation.horizontal",
    "type.orientation.vertical",
    "type.panels.character",
    "type.panels.characterStyles",
    "type.panels.glyphs",
    "type.panels.paragraph",
    "type.panels.paragraphStyles",
    "type.pasteLoremIpsum",
    "type.rasterizeTypeLayer",
    "type.replaceAllMissingFonts",
    "type.resolveMissingFonts",
    "type.saveDefaultTypeStyles",
    "type.updateAllTextLayers",
    "type.warpText",
    "view.extras",
    "view.gamutWarning",
    "view.pixelAspectRatio.anamorphic2To1",
    "view.pixelAspectRatio.d1DvNtsc",
    "view.pixelAspectRatio.d1DvNtscWidescreen",
    "view.pixelAspectRatio.d1DvPal",
    "view.pixelAspectRatio.d1DvPalWidescreen",
    "view.pixelAspectRatio.dvcproHd1080",
    "view.pixelAspectRatio.hdv1080",
    "view.proofSetup.internetStandardRgb",
    "view.proofSetup.legacyMacintoshRgb",
    "view.proofSetup.monitorRgb",
    "view.proofSetup.workingCmyPlate",
    "view.proofSetup.workingCmyk",
    "view.show.mesh",
    "view.twoHundredPercent",
    "window.arrange.cascade",
    "window.arrange.consolidateAllToTabs",
    "window.arrange.fourUp",
    "window.arrange.matchAll",
    "window.arrange.matchRotation",
    "window.arrange.sixUp",
    "window.arrange.threeUpStacked",
    "window.panel.measurementLog",
    "window.panel.modifierKeys",
    "window.panel.timeline",
    "window.workspace.essentials",
    "window.workspace.graphicAndWeb",
    "window.workspace.painting",
    "window.workspace.photography",
    "window.workspace.pixelArt",
];

/// Entries of [`HIDDEN_MENU_ITEMS`] added after version 1, with the version that added them.
pub const HIDDEN_MENU_ADDED: &[(u32, &str)] = &[
    (2, "file.saveACopy"),
    (3, "filter.adaptiveWideAngle"),
];

/// `Tool` enum variant names, as `ToolbarCustomization::hidden` stores them.
pub const HIDDEN_TOOLS: &[&str] = &[
    "Count",
    "HistoryBrush",
    "MagicEraser",
    "Note",
    "Polygon",
    "Triangle",
];
